export const UPDATE_EMAIL_FILTERS = "UPDATE_EMAIL_FILTERS";
export const RESET_EMAIL_FILTERS = "RESET_EMAIL_FILTERS";

export const UPDATE_SELECTED_EMAIL = "UPDATE_SELECTED_EMAIL";
export const RESET_SELECTED_EMAIL = "RESET_SELECTED_EMAIL";

export const UPDATE_FAVORITE_EMAILS = "UPDATE_FAVORITE_EMAILS";
export const ADD_TO_READ = "ADD_TO_READ";
